config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mytasks/', include('mytasks.urls')),
]

mytasks/urls.py
from django.urls import path
from . import views

app_name = 'mytasks'

urlpatterns = [
    path('', views.main, name='main'),
    path('<str:today_url>/', views.today, name='today'),
    path('delete/<int:task_pk>', views.delete, name='delete'),
    path('complete/<int:task_pk>/<str:is_complete>', views.complete, name='complete'),
    path('bt-test', views.bt_test, name='bt_test'),
]

mytasks/models.py
from django.db import models


# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=200)
    contents = models.TextField(null=True, blank=True)
    importance = models.IntegerField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

study_models/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    GRADUATE = 'GR'
    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )

    def is_upperclass(self):
        return self.year_in_school in {self.JUNIOR, self.SENIOR}

mytasks/forms.py
# from .models import

mytasks/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.shortcuts import redirect
from django.utils import timezone

from .models import Task
from .operating_files import obj_date


# 목표 :
# main 페이지 - "오늘" 버튼 만들기
# 버튼을 누르면 오늘 날짜를 얻어와서
# /mytasks/2022-04-03 주소로 리다이렉트


def main(request):
    # Create new task
    if request.method == 'POST':
        input_title = request.POST.get('task_title_input')

        if input_title == '':
            return redirect('mytasks:main')

        new_task = Task()
        new_task.title = input_title
        new_task.created_date = timezone.now()
        new_task.save()

        return redirect('mytasks:main')

    # TodayTasks model
    today_tasks_obj_list = Task.objects.order_by('created_date')

    # datetime obj
    today_obj = obj_date.DateObj()

    # context dictionary
    context = {
        'today_tasks': today_tasks_obj_list,
        'today_obj': today_obj
    }
    return render(request, 'mytasks/main.html', context)


def delete(request, task_pk):
    if request.method == 'POST':
        task = get_object_or_404(Task, pk=task_pk)
        task.delete()
        return redirect('mytasks:main')
    else:
        return redirect('mytasks:main')


def complete(request, task_pk, is_complete):
    if request.method == 'POST':
        if is_complete == 'True':
            task = get_object_or_404(Task, pk=task_pk)
            task.is_completed = False
            task.save()
        else:
            task = get_object_or_404(Task, pk=task_pk)
            task.is_completed = True
            task.save()
        return redirect('mytasks:main')
    else:
        return redirect('mytasks:main')


# postponed function
def today(request, today_url):
    # datetime obj
    today_obj = obj_date.DateObj()

    # TodayTasks model
    today_task_obj_list = Task.objects.order_by('created_date')

    # context
    context = {
        'today_tasks': today_task_obj_list,
        'today_obj': today_obj
    }

    return render(request, 'mytasks/main.html', context)


def bt_test(request):
    return render(request, 'mytasks/base_template_test.html')

study_models/views.py
from django.shortcuts import render

# Create your views here.

templates/mytasks/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {#  bootstrap CSS  #}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/bootstrap.css' %}">


    <title>mytasks</title>


</head>
<body>
<!-- CONTENTS START -->
{% block content %}
{% endblock %}
<!-- CONTENTS END -->


<script src={% static 'dist/js/bootstrap.js' %}></script>
</body>
</html>

templates/mytasks/base_template_test.html
{% extends 'mytasks/base.html' %}
{% block content %}
    <h1 class="my-5">bt-test</h1>


{% endblock %}

templates/mytasks/main.html
{% extends 'mytasks/base.html' %}
{% block content %}
    {# Greeting Message #}
    <div class="container mt-5 mb-4">
        <h1>Hello World </h1>
        <span> 현재 페이지: {{ today_obj.today_url }} </span> <br>
        <span> 현재 시각 : {{ today_obj.today_datetime }}</span>
    </div>

    {# new task POST    #}
    <div class="container">
        <form action="{% url 'mytasks:main' %}" method="POST">
            {% csrf_token %}
            <label>
                <input type="text" name="task_title_input">
            </label>
            <input type="submit" class="btn btn-primary" value="Add task">
        </form>
    </div>


    {#  Bootstrap - Show task  #}

    {# Print TodayTasks Model#}
    <div class="container" id="main-area">
        {% if today_tasks %}
            {% for task in today_tasks %}
                <div class="container m-4 border border-1">
                    <div class="container m-1">
                        <h4>{{ task.title }}</h4>
                        <p>
                            {% if task.contents %}
                                {{ task.contents }}
                                <br>
                            {% endif %}

                            <span>작성일: {{ task.created_date }} </span>
                            <br>
                            <span>중요도: {{ task.importance }}</span>
                            <br>
                            <span>완료여부: {{ task.is_completed }}</span>
                            <br>
                        </p>
                    </div>


                    {#       Delete task button         #}
                    <div class="container m-1">
                        <form action="{% url 'mytasks:delete' task.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Delete" class="btn btn-danger">
                        </form>
                    </div>

                    {#     Complete task button       #}
                    <div class="container m-1">
                        <form action="{% url 'mytasks:complete' task.pk task.is_completed %}" method="post">
                            {% csrf_token %}
                            {% if task.is_completed %}
                                <input type="submit" value="Toggle to incomplete" class="btn btn-dark">
                            {% else %}
                                <input type="submit" value="Complete" class="btn btn-success">
                            {% endif %}

                        </form>
                    </div>

                </div>
            {% endfor %}
        {% else %}
            <h4>There are no today tasks</h4>
        {% endif %}

        <br>

        {#        <a type="button" class="my-2 btn btn-info" href="{% url 'mytasks:today' today_obj.today_url %}">Today</a>#}

        <br>

        {# new task POST    #}
        <form action="{% url 'mytasks:main' %}" method="POST">
            {% csrf_token %}
            <label>
                <input type="text" name="task_title_input">
            </label>
            <input type="submit" class="btn btn-primary" value="Add task">
        </form>


    </div>

    <br><br><br>
    <hr>

    {# Table #}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td colspan="2">Larry the Bird</td>
                <td>@twitter</td>
            </tr>
            </tbody>
        </table>
    </div>

{% endblock %}